//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib_lenguajes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RsDetalles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RsDetalles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lib_lenguajes.RsDetalles", typeof(RsDetalles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANTIDAD.
        /// </summary>
        public static string clCantidad {
            get {
                return ResourceManager.GetString("clCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FACTURA.
        /// </summary>
        public static string clFactura {
            get {
                return ResourceManager.GetString("clFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCTO.
        /// </summary>
        public static string clProducto {
            get {
                return ResourceManager.GetString("clProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL.
        /// </summary>
        public static string clTotal {
            get {
                return ResourceManager.GetString("clTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALOR.
        /// </summary>
        public static string clValor {
            get {
                return ResourceManager.GetString("clValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad: .
        /// </summary>
        public static string lbCantidad {
            get {
                return ResourceManager.GetString("lbCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factura: .
        /// </summary>
        public static string lbFactura {
            get {
                return ResourceManager.GetString("lbFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto: .
        /// </summary>
        public static string lbProducto {
            get {
                return ResourceManager.GetString("lbProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string lbSingular {
            get {
                return ResourceManager.GetString("lbSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: .
        /// </summary>
        public static string lbTotal {
            get {
                return ResourceManager.GetString("lbTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor: .
        /// </summary>
        public static string lbValor {
            get {
                return ResourceManager.GetString("lbValor", resourceCulture);
            }
        }
    }
}
