//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib_lenguajes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RsEmpleados {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RsEmpleados() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lib_lenguajes.RsEmpleados", typeof(RsEmpleados).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARL.
        /// </summary>
        public static string clARL {
            get {
                return ResourceManager.GetString("clARL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARGO.
        /// </summary>
        public static string clCargo {
            get {
                return ResourceManager.GetString("clCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPS.
        /// </summary>
        public static string clEPS {
            get {
                return ResourceManager.GetString("clEPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTADO CIVIL.
        /// </summary>
        public static string clEstadoCivil {
            get {
                return ResourceManager.GetString("clEstadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FONDO PEN..
        /// </summary>
        public static string clPension {
            get {
                return ResourceManager.GetString("clPension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERSONA.
        /// </summary>
        public static string clPersona {
            get {
                return ResourceManager.GetString("clPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIPO SANGRE.
        /// </summary>
        public static string clTipoSangre {
            get {
                return ResourceManager.GetString("clTipoSangre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARL: .
        /// </summary>
        public static string lbARL {
            get {
                return ResourceManager.GetString("lbARL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo: .
        /// </summary>
        public static string lbCargo {
            get {
                return ResourceManager.GetString("lbCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPS: .
        /// </summary>
        public static string lbEPS {
            get {
                return ResourceManager.GetString("lbEPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado civil: .
        /// </summary>
        public static string lbEstadoCivil {
            get {
                return ResourceManager.GetString("lbEstadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fondo de pensiones:.
        /// </summary>
        public static string lbPension {
            get {
                return ResourceManager.GetString("lbPension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona: .
        /// </summary>
        public static string lbPersona {
            get {
                return ResourceManager.GetString("lbPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleado.
        /// </summary>
        public static string lbSingular {
            get {
                return ResourceManager.GetString("lbSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo sangre: .
        /// </summary>
        public static string lbTipoSangre {
            get {
                return ResourceManager.GetString("lbTipoSangre", resourceCulture);
            }
        }
    }
}
