//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib_lenguajes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RsErrores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RsErrores() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lib_lenguajes.RsErrores", typeof(RsErrores).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error guardando en base de datos.
        /// </summary>
        public static string lbErrorBaseDeDatos {
            get {
                return ResourceManager.GetString("lbErrorBaseDeDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe el ciudad.
        /// </summary>
        public static string lbExisteCiudad {
            get {
                return ResourceManager.GetString("lbExisteCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe el departamento.
        /// </summary>
        public static string lbExisteDepartamento {
            get {
                return ResourceManager.GetString("lbExisteDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe el empleado.
        /// </summary>
        public static string lbExisteEmpleado {
            get {
                return ResourceManager.GetString("lbExisteEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe el pais.
        /// </summary>
        public static string lbExistePais {
            get {
                return ResourceManager.GetString("lbExistePais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe el proveedor.
        /// </summary>
        public static string lbExisteProveedor {
            get {
                return ResourceManager.GetString("lbExisteProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe el tipo.
        /// </summary>
        public static string lbExisteTipo {
            get {
                return ResourceManager.GetString("lbExisteTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el ciudad.
        /// </summary>
        public static string lbNoExisteCiudad {
            get {
                return ResourceManager.GetString("lbNoExisteCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el departamento.
        /// </summary>
        public static string lbNoExisteDepartamento {
            get {
                return ResourceManager.GetString("lbNoExisteDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el empleado.
        /// </summary>
        public static string lbNoExisteEmpleado {
            get {
                return ResourceManager.GetString("lbNoExisteEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el pais.
        /// </summary>
        public static string lbNoExistePais {
            get {
                return ResourceManager.GetString("lbNoExistePais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el proveedor.
        /// </summary>
        public static string lbNoExisteProveedor {
            get {
                return ResourceManager.GetString("lbNoExisteProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el tipo.
        /// </summary>
        public static string lbNoExisteTipo {
            get {
                return ResourceManager.GetString("lbNoExisteTipo", resourceCulture);
            }
        }
    }
}
