//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib_lenguajes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RsFacturas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RsFacturas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lib_lenguajes.RsFacturas", typeof(RsFacturas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVO.
        /// </summary>
        public static string clActivo {
            get {
                return ResourceManager.GetString("clActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FECHA.
        /// </summary>
        public static string clFecha {
            get {
                return ResourceManager.GetString("clFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MET. PAGO.
        /// </summary>
        public static string clMetodoPago {
            get {
                return ResourceManager.GetString("clMetodoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NÚMERO.
        /// </summary>
        public static string clNumero {
            get {
                return ResourceManager.GetString("clNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERSONA.
        /// </summary>
        public static string clPersona {
            get {
                return ResourceManager.GetString("clPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIPO.
        /// </summary>
        public static string clTipo {
            get {
                return ResourceManager.GetString("clTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL.
        /// </summary>
        public static string clTotal {
            get {
                return ResourceManager.GetString("clTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo: .
        /// </summary>
        public static string lbActivo {
            get {
                return ResourceManager.GetString("lbActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha: .
        /// </summary>
        public static string lbFecha {
            get {
                return ResourceManager.GetString("lbFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metodo de pago: .
        /// </summary>
        public static string lbMetodoPago {
            get {
                return ResourceManager.GetString("lbMetodoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número: .
        /// </summary>
        public static string lbNumero {
            get {
                return ResourceManager.GetString("lbNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona.
        /// </summary>
        public static string lbPersona {
            get {
                return ResourceManager.GetString("lbPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factura.
        /// </summary>
        public static string lbSingular {
            get {
                return ResourceManager.GetString("lbSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo: .
        /// </summary>
        public static string lbTipo {
            get {
                return ResourceManager.GetString("lbTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: .
        /// </summary>
        public static string lbTotal {
            get {
                return ResourceManager.GetString("lbTotal", resourceCulture);
            }
        }
    }
}
