//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib_lenguajes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RsMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RsMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lib_lenguajes.RsMenu", typeof(RsMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        public static string lbAction {
            get {
                return ResourceManager.GetString("lbAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string lbActivo {
            get {
                return ResourceManager.GetString("lbActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2024.
        /// </summary>
        public static string lbAño {
            get {
                return ResourceManager.GetString("lbAño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoteles+.
        /// </summary>
        public static string lbApp {
            get {
                return ResourceManager.GetString("lbApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea borrar la siguiente información?.
        /// </summary>
        public static string lbBorrarEntidad {
            get {
                return ResourceManager.GetString("lbBorrarEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string lbCerrar {
            get {
                return ResourceManager.GetString("lbCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamentos.
        /// </summary>
        public static string lbDepartamentos {
            get {
                return ResourceManager.GetString("lbDepartamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string lbEntrar {
            get {
                return ResourceManager.GetString("lbEntrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivo.
        /// </summary>
        public static string lbInactivo {
            get {
                return ResourceManager.GetString("lbInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string lbInicio {
            get {
                return ResourceManager.GetString("lbInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar.
        /// </summary>
        public static string lbLimpiar {
            get {
                return ResourceManager.GetString("lbLimpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        public static string lbMensaje {
            get {
                return ResourceManager.GetString("lbMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paises.
        /// </summary>
        public static string lbPaises {
            get {
                return ResourceManager.GetString("lbPaises", resourceCulture);
            }
        }
    }
}
