//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib_lenguajes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RsPersonas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RsPersonas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lib_lenguajes.RsPersonas", typeof(RsPersonas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVO.
        /// </summary>
        public static string clActivo {
            get {
                return ResourceManager.GetString("clActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CELULAR.
        /// </summary>
        public static string clCelular {
            get {
                return ResourceManager.GetString("clCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIUDAD.
        /// </summary>
        public static string clCiudad {
            get {
                return ResourceManager.GetString("clCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRMAR.
        /// </summary>
        public static string clConfirmar {
            get {
                return ResourceManager.GetString("clConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTRASEÑA.
        /// </summary>
        public static string clContraseña {
            get {
                return ResourceManager.GetString("clContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIRECCIÓN.
        /// </summary>
        public static string clDireccion {
            get {
                return ResourceManager.GetString("clDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOCUMENTO.
        /// </summary>
        public static string clDocumento {
            get {
                return ResourceManager.GetString("clDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        public static string clEmail {
            get {
                return ResourceManager.GetString("clEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FECHA NAC..
        /// </summary>
        public static string clFechaNacimiento {
            get {
                return ResourceManager.GetString("clFechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERO.
        /// </summary>
        public static string clGenero {
            get {
                return ResourceManager.GetString("clGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOMBRE.
        /// </summary>
        public static string clNombre {
            get {
                return ResourceManager.GetString("clNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESTABLECER.
        /// </summary>
        public static string clRestablecer {
            get {
                return ResourceManager.GetString("clRestablecer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIPO DOC..
        /// </summary>
        public static string clTipoDocumento {
            get {
                return ResourceManager.GetString("clTipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOKEN.
        /// </summary>
        public static string clToken {
            get {
                return ResourceManager.GetString("clToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo: .
        /// </summary>
        public static string lbActivo {
            get {
                return ResourceManager.GetString("lbActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular: .
        /// </summary>
        public static string lbCelular {
            get {
                return ResourceManager.GetString("lbCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad: .
        /// </summary>
        public static string lbCiudad {
            get {
                return ResourceManager.GetString("lbCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar: .
        /// </summary>
        public static string lbConfirmar {
            get {
                return ResourceManager.GetString("lbConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña: .
        /// </summary>
        public static string lbContraseña {
            get {
                return ResourceManager.GetString("lbContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección: .
        /// </summary>
        public static string lbDireccion {
            get {
                return ResourceManager.GetString("lbDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento: .
        /// </summary>
        public static string lbDocumento {
            get {
                return ResourceManager.GetString("lbDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: .
        /// </summary>
        public static string lbEmail {
            get {
                return ResourceManager.GetString("lbEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha nacimiento: .
        /// </summary>
        public static string lbFechaNacimiento {
            get {
                return ResourceManager.GetString("lbFechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genero: .
        /// </summary>
        public static string lbGenero {
            get {
                return ResourceManager.GetString("lbGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre: .
        /// </summary>
        public static string lbNombre {
            get {
                return ResourceManager.GetString("lbNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restablecer: .
        /// </summary>
        public static string lbRestablecer {
            get {
                return ResourceManager.GetString("lbRestablecer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona.
        /// </summary>
        public static string lbSingular {
            get {
                return ResourceManager.GetString("lbSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo documento: .
        /// </summary>
        public static string lbTipoDocumento {
            get {
                return ResourceManager.GetString("lbTipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token: .
        /// </summary>
        public static string lbToken {
            get {
                return ResourceManager.GetString("lbToken", resourceCulture);
            }
        }
    }
}
