//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib_lenguajes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RsProductos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RsProductos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lib_lenguajes.RsProductos", typeof(RsProductos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANT..
        /// </summary>
        public static string clCantidad {
            get {
                return ResourceManager.GetString("clCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORIA.
        /// </summary>
        public static string clCategoria {
            get {
                return ResourceManager.GetString("clCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÓDIGO.
        /// </summary>
        public static string clCodigo {
            get {
                return ResourceManager.GetString("clCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COSTO.
        /// </summary>
        public static string clCosto {
            get {
                return ResourceManager.GetString("clCosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FECHA ING..
        /// </summary>
        public static string clFechaIngreso {
            get {
                return ResourceManager.GetString("clFechaIngreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FECHA VEN..
        /// </summary>
        public static string clFechaVencimiento {
            get {
                return ResourceManager.GetString("clFechaVencimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOTE.
        /// </summary>
        public static string clLote {
            get {
                return ResourceManager.GetString("clLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOMBRE.
        /// </summary>
        public static string clNombre {
            get {
                return ResourceManager.GetString("clNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROVEEDOR.
        /// </summary>
        public static string clProveedor {
            get {
                return ResourceManager.GetString("clProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALOR.
        /// </summary>
        public static string clValor {
            get {
                return ResourceManager.GetString("clValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad: .
        /// </summary>
        public static string lbCantidad {
            get {
                return ResourceManager.GetString("lbCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria: .
        /// </summary>
        public static string lbCategoria {
            get {
                return ResourceManager.GetString("lbCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string lbCodigo {
            get {
                return ResourceManager.GetString("lbCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo: .
        /// </summary>
        public static string lbCosto {
            get {
                return ResourceManager.GetString("lbCosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha ingreso: .
        /// </summary>
        public static string lbFechaIngreso {
            get {
                return ResourceManager.GetString("lbFechaIngreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechavencimiento: .
        /// </summary>
        public static string lbFechaVencimiento {
            get {
                return ResourceManager.GetString("lbFechaVencimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lote: .
        /// </summary>
        public static string lbLote {
            get {
                return ResourceManager.GetString("lbLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre: .
        /// </summary>
        public static string lbNombre {
            get {
                return ResourceManager.GetString("lbNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor: .
        /// </summary>
        public static string lbProveedor {
            get {
                return ResourceManager.GetString("lbProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        public static string lbSingular {
            get {
                return ResourceManager.GetString("lbSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor: .
        /// </summary>
        public static string lbValor {
            get {
                return ResourceManager.GetString("lbValor", resourceCulture);
            }
        }
    }
}
